### ISSUE TITLE
Add optional caption between embed and credit

### ISSUE THREAD

**Issue by lindamood** [nprapps/bestmusic16#108]
The embeds don't identify which song appears in the album modal.

**Comment by lindamood** [comment]
@TylerFisher I'm assigning this to you to assess feasibility. Can this be a task that @brmayes takes in between helping Otis with the spreadsheet and testing?

**Comment by brmayes** [comment]
@lindamood will all optional captions be song titles? Just need to know if I should bake in quotes around the field in the template or if I should leave that to be filled in on the spreadsheet.

**Comment by lindamood** [comment]
leave it to be filled in on the spreadsheet.
