### ISSUE TITLE
Detail modal: design

### ISSUE THREAD

**Issue by lindamood** [nprapps/bestmusic16#11]
<img width="475" alt="design_review__best_music_2016_-_google_slides" src="https://cloud.githubusercontent.com/assets/1319852/20317343/a76fe258-ab33-11e6-9c09-3c7254efeba0.png">

**Comment by lindamood** [comment]
@brmayes here's a revised desktop modal design. Let's talk through any implications this has on the small screen design.

![strike-a-balance](https://cloud.githubusercontent.com/assets/1319852/20439316/f8369964-ad88-11e6-9311-9f7ba2d9ddb0.png)

**Comment by brmayes** [comment]
This is ready to pass to Wes for small changes. Going to close this.
