### ISSUE TITLE
Frank Ocean Apple Music embed causes horizontal scroll

### ISSUE THREAD

**Issue by TylerFisher** [nprapps/bestmusic16#124]
![screen shot 2016-12-02 at 10 11 09 am](https://cloud.githubusercontent.com/assets/1077075/20838716/c23a5f0e-b877-11e6-8cf5-1a3202486c13.png)

**Comment by lindamood** [comment]
The apple music embed cannot be resized. We can pull it or get permission to use the vimeo one.
