### ISSUE TITLE
Schedule design review with brittany

### ISSUE THREAD

**Issue by lindamood** [nprapps/bestmusic16#17]
after first pass at all the layouts

**Comment by lindamood** [comment]
@brmayes For this review let's take a close look at the index, list, and detail modal. Would these views be polished enough by later today _(Wednesday)_ that we could schedule something for around 4PM?

**Comment by brmayes** [comment]
@lindamood 4 sounds good. Will definitely have at least the index and list view polished enough. I'll keep you updated on the modal.
