### ISSUE TITLE
consider modal animation when modal opens and closes

### ISSUE THREAD

**Issue by lindamood** [nprapps/bestmusic16#29]

**Comment by lindamood** [comment]
@brmayes Curious if you have a preference here? I like the modal animation on http://apps.npr.org/best-books-2015/ , which I think is a bootstrap default.

The fade in & scale for this modal could also work well:
http://tympanus.net/Development/ModalWindowEffects/
https://github.com/sd6352051/NiftyDialogEffects

I guess it depends what code works best with the modal approach you and @TylerFisher have already started to build.

**Comment by lindamood** [comment]
I like how the "just me" animation in this modal works on mobile: http://tympanus.net/Development/ModalWindowEffects/

**Comment by brmayes** [comment]
decided to do fade in and scale for desk and just me for mobile.

**Comment by brmayes** [comment]
this is implemented.
