### ISSUE TITLE
How should the modal work on split type lists?

### ISSUE THREAD

**Issue by TylerFisher** [nprapps/bestmusic16#43]
Should the modal loop through all songs and albums? Or should it loop through just the type you've clicked into?

**Comment by lindamood** [comment]
all songs and albums, i think.

**Comment by lindamood** [comment]
![best-music-2016-wireframes__desktop](https://cloud.githubusercontent.com/assets/1319852/20365963/14f61a02-ac17-11e6-9067-57fca2fd5e4b.png)
We'll want to update this text accordingly.

**Comment by TylerFisher** [comment]
Done in 77c5d55d12ddd855ccebf0f28d5863b3aaffeccb
