### ISSUE TITLE
Design exploration: add "play highlights on Spotify" button to the top of list pages.

### ISSUE THREAD

**Issue by lindamood** [nprapps/bestmusic16#48]

**Comment by lindamood** [comment]
@TylerFisher @brmayes Here's a design exploration that includes a Spotify playlist button on list pages. I'll leave this ticket open until we know if it's technically feasible to do this. 

When we do our next ticket shuffle, which I'll schedule for Monday, 11/28, we can review.

![best-music-2016-wireframes__desktop](https://cloud.githubusercontent.com/assets/1319852/20405432/02835dd8-acd7-11e6-8f54-f00310738caf.png)

![best-music-2016-wireframes__mobile_1](https://cloud.githubusercontent.com/assets/1319852/20405439/0ba39bd0-acd7-11e6-9a6e-e9c1b0823052.png)

**Comment by lindamood** [comment]
This will just be a link to the spotify playlist. Otis is cool with the design.

**Comment by TylerFisher** [comment]
Built. Assigning to @brmayes for design.
