### ISSUE TITLE
Design: create stronger differentiation between headlines and subheads on list pages.

### ISSUE THREAD

**Issue by lindamood** [nprapps/bestmusic16#49]

**Comment by lindamood** [comment]
Something to think about when you're working on design refinements. Here's a quick exploration that attempts to address this.

![best-music-2016-wireframes__desktop](https://cloud.githubusercontent.com/assets/1319852/20402136/86e692a6-acc9-11e6-85f4-1e75a6620028.png)

**Comment by brmayes** [comment]
Finished with last commit.
