### ISSUE TITLE
Favorites button: development

### ISSUE THREAD

**Issue by lindamood** [nprapps/bestmusic16#6]
button design should change if favorites have been added.

<img width="102" alt="design_review__best_music_2016_-_google_slides" src="https://cloud.githubusercontent.com/assets/1319852/20317008/4ba7c6b2-ab32-11e6-8aad-f8eaa952e32f.png">

**Comment by TylerFisher** [comment]
Done on the favorites branch, will merge in when modal DOM structure is clearer.
