### ISSUE TITLE
Browser testing

### ISSUE THREAD

**Issue by lindamood** [nprapps/bestmusic16#60]
- [x] Browser testing: IE11
- [x] Browser testing: Latest Firefox
- [x] Browser testing: Latest Chrome
- [x] Browser testing: Desktop Safari
- [x] Device testing: iPhone Safari
- [x] Device testing: iPhone Chrome/Webkit
- [ ] Device testing: iPhone in-app browser
- [x] Device testing: Facebook in-app browser
- [x] Device testing: Twitter in-app browser
- [x] Device testing: iPad
- [x] Device testing: Android phone
- [ ] Device testing: Android tablet

**Comment by lindamood** [comment]
@brmayes there is an iPad you can test with in the cabinets below the scanner on the other side of my desk.

**Comment by lindamood** [comment]
@brmayes if you can't find an android tablet, don't worry about it. See if you can borrow Juan's phone for testing, so we can get a version of Android that's different from Eads.

**Comment by TylerFisher** [comment]
Checked IE11. Closing this.
